-- CREATE TABLE IF NOT EXISTS INVOICE (
--     ID INTEGER NOT NULL,
--     NAME VARCHAR(255) NOT NULL,
--     AMOUNT INTEGER NOT NULL,
--     FINAL_AMOUNT INTEGER NOT NULL,
--     NUMBER INTEGER NOT NULL,
--     RECEIVED_DATE DATE NOT NULL,
--     TYPE VARCHAR(255) NOT NULL,
--     VENDOR VARCHAR(255) NOT NULL,
--     COMMENTS VARCHAR(255) NOT NULL
--     );

SELECT ID, NAME, AMOUNT, FINAL_AMOUNT, NUMBER, RECEIVED_DATE, TYPE, VENDOR, COMMENTS FROM Invoice